# Generated by Django 3.2.4 on 2021-06-13 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='message',
        ),
    ]
