# Generated by Django 3.2.4 on 2021-06-13 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_message_predict_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='password',
            new_name='description',
        ),
    ]
