# Generated by Django 3.2.4 on 2021-10-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_password_message_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='username',
            new_name='sentence',
        ),
    ]
